version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: devweb1-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: devweb1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
